### Identity Matrix

In [ ]:
'''
Identity Matrix (Important Questions)

Q1. What is an identity matrix?
Ans. An identity matrix is a square matrix that leaves vectors and matrices unchanged when multiplied.
'''
# Example
# I = [[1, 0],
#      [0, 1]]
# I × v = v


'''
Q2. Why is the identity matrix called the matrix version of 1?
Ans. Because multiplying any compatible matrix or vector by it gives the same object back, just like multiplying by 1.
'''
# Example
# A × I = A
# I × A = A


'''
Q3. What is the shape requirement of an identity matrix?
Ans. An identity matrix must always be square with shape (n, n).
'''
# Example
# I3 has shape (3, 3)
# I5 has shape (5, 5)


'''
Q4. What happens geometrically when you multiply by the identity matrix?
Ans. There is no transformation—no rotation, no scaling, no reflection.
'''
# Example
# Original vector v remains unchanged after multiplication


'''
Q5. Why is the identity matrix important in AI and ML?
Ans. It helps preserve information and is used in skip connections, inverses, and stable transformations.
'''
# Example
# Residual connection: output = x + F(x)
# Conceptually preserves x (identity behavior)


'''
Q6. What is a common mistake when using identity matrices?
Ans. Using an identity matrix of the wrong size for multiplication.
'''
# Example
# I3 × vector(4×1) → ❌ invalid
# I4 × vector(4×1) → ✅ valid


### Identity does nothing to a Vector/Matrix

In [1]:
import numpy as np

I = np.eye(2)
v = np.array([[3],
              [7]])

print(I @ v)
# [[3]
#  [7]]


[[3.]
 [7.]]


### Why is it the matrix version of 1?

In [2]:
# Because it's like multiplying by 1, has no impact.

A = np.array([[1, 2],
              [3, 4]])

I = np.eye(2)

print(A @ I)
print(I @ A)


[[1. 2.]
 [3. 4.]]
[[1. 2.]
 [3. 4.]]


### Geometrically

In [3]:
# No rotation
# No scaling
# No reflection

### Concise Summary

In [ ]:
cs = '''
Identity Matrix (I):

• Square matrix → shape (n, n)
• 1s on the main diagonal
• 0s everywhere else
• Matrix version of number 1


Core Properties:
• I × v = v           → multiplying a vector changes nothing
• A × I = A           → right identity
• I × A = A           → left identity
• I × I = I           → identity stays identity
• I⁻¹ = I             → inverse of identity is itself
• Iᵀ = I              → transpose does not change it
• det(I) = 1          → determinant is 1
• rank(I) = n         → full rank
• eigenvalues = 1     → all eigenvalues are 1


Geometric Meaning:
• No rotation
• No scaling
• No distortion
• No change of space


AI / ML Meaning:
• Preserves information
• Keeps embeddings in the same semantic space
• Used in residual (skip) connections
• Acts as “do nothing but allow flow”
• Used for numerical stability
• Implicitly used in similarity search (RAG, vector DBs)


Where it appears in AI:
• Residual connections:  x + F(x)
• RAG retrieval: raw embedding comparison
• Identity initialization
• Regularization and stability tricks


Mental Rule (IMPORTANT):
Identity does nothing —
but allows learning, stability, and information flow.

'''