In [ ]:
'''
Q1. What do rows represent in AI datasets?
Ans. Rows represent data points or samples — each row is one example.
'''
# Example
# (50, 5)
# 50 rows → 50 students
# Each row = one student’s data


'''
Q2. What do columns represent in AI datasets?
Ans. Columns represent features — each column is one type of information.
'''
# Example
# (50, 5)
# 5 columns → 5 features (age, height, weight, marks, grade)


'''
Q3. What does a shape like (50, 5) mean exactly?
Ans. It means 50 data points, each with 5 features.
'''
# Example
# Student dataset:
# Row = one student
# Column = one feature


'''
Q4. What is a row vector?
Ans. A row vector is a vector written as a single row.
'''
# Example
# Shape: (1, 5)
row_vector = [[2, 4, 6, 8, 10]]


'''
Q5. What is a column vector?
Ans. A column vector is a vector written as a single column.
'''
# Example
# Shape: (5, 1)
column_vector = [
    [2],
    [4],
    [6],
    [8],
    [10]
]

# Visually it can also look like this:
column_vector_visual = [[2], [4], [6], [8], [10]] # actually the same as above


'''
Q6. Why do row vs column vectors matter in AI?
Ans. Because even with the same numbers, different shapes lead to different math results.
'''
# Example
# Row vector  (1,5) · Column vector (5,1) → scalar ✔️
# Column (5,1) · Row (1,5) → matrix (5,5) ✔️
# Same numbers, very different results!


'''
Q7. What is the critical rule to remember?
Ans. Shape controls math — same values with different shapes behave differently.
'''
# Example (mental rule)
# Numbers ≠ shape
# Shape decides what operations are allowed.
# Always check shapes before doing math!


'''
Q8. Why do neural networks care so much about row vs column vectors?
Ans. Because inputs are usually column vectors and weights are matrices, so shapes must match exactly.
'''
# Example
# W shape = (10, 5)
# x shape = (5, 1)
# Output: W × x → (10, 1) ✔️
# Wrong shape → ❌ error

# ==========  SET-2. ============


'''
Q1. Why do the same numbers behave differently when shape changes?
Ans. Because math operations depend on shape, not just values. Shape tells math how to combine numbers.
'''
# Example
# Same numbers: 1 2 3 4 5 6
import numpy as np
A = [[1, 2, 3, 4, 5, 6]]        # shape (1, 6) → row vector
B = [[1],[2],[3],[4],[5],[6]]# shape (6, 1) → column vector
# or
A = np.array([[1, 2, 3, 4, 5, 6]])   # (1, 6) row vector
B = np.array([[1],[2],[3],[4],[5],[6]])  # (6, 1) column vector

'''
Q2. What is the core rule of matrix multiplication?
Ans. The inside dimensions must match: (m × n) · (n × k) → (m × k).
'''
# Example
# (1, 6) · (6, 1) → (1, 1)
# (6, 1) · (1, 6) → (6, 6)


'''
Q3. What happens when we multiply a row vector by a column vector?
Ans. It produces a single number (a scalar).
'''
# Example
# A shape = (1, 6)
# B shape = (6, 1)
# A · B = 1*1 + 2*2 + ... + 6*6 = 91
# Result shape = (1, 1)


'''
Q4. What happens when we multiply a column vector by a row vector?
Ans. It produces a full matrix.
'''
# Example
# B shape = (6, 1)
# A shape = (1, 6)
# B · A → shape (6, 6)
# Result is a big table of numbers


'''
Q5. How does shape change the meaning of data in AI?
Ans. Shape decides whether data is interpreted as “many features” or “many samples.”
'''
# Example
# (1, 3) → one sample with 3 features
# X1 = [height, weight, age]

# (3, 1) → three samples with one feature
# X2 = [
#     [height],
#     [weight],
#     [age]
# ]


'''
Q6. Why do neural networks care so much about shape?
Ans. Because layers expect inputs in exact shapes. Wrong shape breaks the math.
'''
# Example
# Model expects: (32, 128)
# You give:        (128, 32)
# ❌ Shapes mismatch → model fails or learns wrongly


'''
Q7. What is broadcasting and why is it dangerous?
Ans. Broadcasting automatically stretches shapes, which can silently change behavior without errors.
'''
# Example
# A shape = (3, 3)
# b shape = (1, 3)
# A + b → b repeats across rows

# If b shape = (3, 1)
# A + b → b repeats down columns (different result!)


q='''
Q8. What is the one killer rule to remember?
Ans. Numbers store data, but SHAPE tells math what to do with that data.
'''
# Example (lock it 🔒)
# Same values + different shapes = different math behavior


### Row Vector

In [1]:
import numpy as np

row_vector = np.array([[2, 4, 6, 8, 10]])
print(row_vector.shape)   # (1, 5)
print(row_vector.ndim)    # 2


(1, 5)
2


### Column Vector

In [2]:
column_vector = np.array([
    [2],
    [4],
    [6],
    [8],
    [10]
])

print(column_vector.shape)  # (5, 1)
print(column_vector.ndim)   # 2


(5, 1)
2


### Row and Column (their correctness matters)

In [7]:
row = np.array([[1, 2, 3]])      # (1, 3)
col = np.array([[1], [2], [3]]) # (3, 1)

print(f"Result of row @ col: {row @ col}")
print(f"Shape of result: {(row @ col).shape}")  # (1, 1)

print(f"Result of col @ row:\n{col @ row}")
print(f"Shape of result: {(col @ row).shape}")  # (3,

# 📌 Same values.
# 📌 Completely different math.
# 📌 Shape controls behavior.

Result of row @ col: [[14]]
Shape of result: (1, 1)
Result of col @ row:
[[1 2 3]
 [2 4 6]
 [3 6 9]]
Shape of result: (3, 3)


### Broadcasting : Powerful but dangerous

In [11]:
# Broadcasting :
#  
# Broadcasting is a feature in NumPy 
# - that allows arrays with different shapes to be used in arithmetic operations.
# It automatically "stretches" smaller arrays to match the shape of larger ones, enabling element-wise operations.
# However, it can be dangerous because it silently changes behavior without errors.


# Broadcasting Example :
A = np.array([[1, 2, 3, 4, 5, 6]])   # (1, 6) row vector
b = np.array([[10, 20, 30, 40, 50, 60]])  # (1, 6) row vector
C = A + b  # Both have shape (1, 6), so they align perfectly
print("NO BRADCASTING HERE...")
print("C (A + b) :", C)  
print("C (A + b) shape:", C.shape)  # Output: (1, 6)

# ------------------------------------------------------------------------

b = np.array([[10], [20], [30], [40], [50], [60]])  # (6, 1) column vector
D = A + b  # Broadcasting occurs here
print("BROADCASTING HERE...")
print("D (A + b) :", D)
print("D (A + b) shape:", D.shape)  # Output: (6, 6)


NO BRADCASTING HERE...
C (A + b) : [[11 22 33 44 55 66]]
C (A + b) shape: (1, 6)
BROADCASTING HERE...
D (A + b) : [[11 12 13 14 15 16]
 [21 22 23 24 25 26]
 [31 32 33 34 35 36]
 [41 42 43 44 45 46]
 [51 52 53 54 55 56]
 [61 62 63 64 65 66]]
D (A + b) shape: (6, 6)


In [12]:
# 🧠 One Ultimate Mental Model (lock 🔒)

# Shape = grammar
# Numbers = words
# Same words + different grammar = different meaning