In [2]:
'''
Q1. What does transpose mean in simple words?
Ans. Transpose means flipping rows and columns — like turning a table sideways.
'''
# Example
# Before (column vector):
# [1]
# [2]
# [3]
#
# After transpose:
# [1  2  3]


'''
Q2. What happens when you transpose a vector?
Ans. A column vector becomes a row vector, and a row vector becomes a column vector.
'''
# Example
# x shape = (5, 1)
# xᵀ shape = (1, 5)


'''
Q3. What happens when you transpose a matrix?
Ans. Rows become columns, and columns become rows.
'''
# Example
# Original (2, 3):
# [1  2  3]
# [4  5  6]
#
# Transpose (3, 2):
# [1  4]
# [2  5]
# [3  6]


'''
Q4. How do shapes change after transpose?
Ans. If a matrix has shape (m, n), after transpose it becomes (n, m).
'''
# Example
# A shape = (2, 3)
# Aᵀ shape = (3, 2)


'''
Q5. Why is transpose important in AI?
Ans. Transpose helps align shapes correctly for math operations like dot products and matrix multiplication.
'''
# Example
# W shape = (10, 5)
# x shape = (5, 1)
# W × x works ✔️
# If x was (1, 5), we need xᵀ


'''
Q6. Where do we see transpose used a lot in AI models?
Ans. In neural networks, dot products, attention mechanisms, and when converting row data into column inputs.
'''
# Example
# Dataset row → transpose → column input for a neural network


q='''
Q7. What is the one rule you must always remember about transpose?
Ans. Transpose swaps rows and columns — shape (m, n) becomes (n, m).
'''
# Example (lock it 🔒)
# Rows ↔ Columns


### Transpose a Vector

In [3]:
import numpy as np

x = np.array([[0.1], [0.2], [0.3]])  # shape (3, 1)

x_T = x.T

print(f"Original Array/Vector : {x}")
print(f"Original Shape: {x.shape}")      # (3, 1)

print(f"Transposed Array/Vector : {x_T}")
print(f"Transposed Shape: {x_T.shape}")  # (1, 3)

Original Array/Vector : [[0.1]
 [0.2]
 [0.3]]
Original Shape: (3, 1)
Transposed Array/Vector : [[0.1 0.2 0.3]]
Transposed Shape: (1, 3)


In [4]:
# 📌 Column → Row
# 📌 Row → Column

# This is critical in neural networks.

### Transpose only works from 2D Matrix (It does not work on 1D vectors)

In [ ]:
vector = np.array([1, 2, 3])  # shape (3, )

vector_T = vector.T

print(f"Original Vector : {vector}")
print(f"Original Shape: {vector.shape}")      # (3, )   

print(f"Transposed Vector : {vector_T}")
print(f"Transposed Shape: {vector_T.shape}")  # (3, )
# Very Important : A 1D array's transpose does not change its shape.
# This is because -> (3,) : has no row/column distinction
# Transpose only works meaningfully for 2-D arrays

Original Vector : [1 2 3]
Original Shape: (3,)
Transposed Vector : [1 2 3]
Transposed Shape: (3,)


### Transpose a Matrix

In [6]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])  # shape (2, 3)

matrix_T = matrix.T

print(f"Original Matrix : \n{matrix}")
print(f"Original Shape: {matrix.shape}")      # (2, 3)

print(f"Transposed Matrix : \n{matrix_T}")
print(f"Transposed Shape: {matrix_T.shape}")  # (3, 2)

Original Matrix : 
[[1 2 3]
 [4 5 6]]
Original Shape: (2, 3)
Transposed Matrix : 
[[1 4]
 [2 5]
 [3 6]]
Transposed Shape: (3, 2)


### Transposing a Matrix (with Pure Python)

In [16]:
matrix = np.array([[1, 2, 3],   
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])  # shape (4, 3)  

# VISUALIZATION : This helps in visualization of how zip helps in transposing a matrix.
for new_row in zip(*matrix):
    print(new_row)
    print(list(new_row))
    print(np.array(list(new_row)), "\n")

# ACTUAL : let's now finish transposing and creating new matrix
transposed_matrix = np.array([list(new_row) for new_row in zip(*matrix)])
print(f"\n\nTransposed Matrix : \n{transposed_matrix}")

(np.int64(1), np.int64(4), np.int64(7), np.int64(10))
[np.int64(1), np.int64(4), np.int64(7), np.int64(10)]
[ 1  4  7 10] 

(np.int64(2), np.int64(5), np.int64(8), np.int64(11))
[np.int64(2), np.int64(5), np.int64(8), np.int64(11)]
[ 2  5  8 11] 

(np.int64(3), np.int64(6), np.int64(9), np.int64(12))
[np.int64(3), np.int64(6), np.int64(9), np.int64(12)]
[ 3  6  9 12] 



Transposed Matrix : 
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


### Why transpose matters in AI ?

In [ ]:
# X is a single input sample with 3 features
# W contains weights for 2 neurons, each with 3 features
import numpy as np

# One linear layer in a neural network
# 3 input features → 2 neurons

X = np.array([[1, 2, 3]])      # input sample (1, 3)
W = np.array([[1, 0, 1],       # weights (neurons, features)
              [0, 1, 1]])      # shape (2, 3)

# ❌ Wrong: shape mismatch
# X @ W        # (1,3) @ (2,3) → invalid

# ✅ Correct: transpose aligns features
Y = X @ W.T   # (1,3) @ (3,2) → (1,2)

print(Y)

### Transpose helping in Attention Mechanism

In [18]:
# Attention mechanism example
import numpy as np
Q = np.array([[1, 0, 0]])      # Query (1, 3)
K = np.array([[1, 2, 3],       # Keys (4, 3)
              [0, 1, 0],
              [1, 0, 1],
              [0, 0, 1]])  # shape (4, 3)
K_T = K.T                        # Transposed Keys (3, 4)   
attention_scores = Q @ K_T      # (1, 3) @ (3, 4) → (1, 4)
print(attention_scores)


# Here Transpose helps align the shapes for the dot product between Q and K.

[[1 0 1 0]]


In [20]:
# ✅ Q6. Where transpose appears in AI — (✔ Correct)

# Common real usages:
# Input formatting
# Dot products
# Attention scores
# Loss calculations
# Gradients (very heavy use)

In [21]:
# 🧠 Mental Model (keep this forever)

# Transpose = rotate the data’s viewpoint
# Values stay same
# Meaning changes because shape changes

In [ ]:
# Throw the dice 10 times what is the probability that sum of the numbers is 10?
